# @token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imh1eWh1eWh1eSIsImlkIjo0LCJpYXQiOjE3NjQzNDA4MTksImV4cCI6MTc2NDM0MjYxOX0.hC0Z6i1FeB7zXWbUrjpamsIU44_4gOUBOj6QmqbhrYs

@token = {{login.response.body.token}}
@id=4
###
# @name login
POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "huyhuyhuy",
    "password": "123"
}

###
POST http://localhost:3000/signup
Content-Type: application/json

{
    "username": "huyhuyhuy",
    "password": "123"
}
###
GET http://localhost:3000
###
POST http://localhost:3000/test
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "username": "bob456",
    "password": "hash_bob"
}

###
GET http://localhost:3000/users/{{id}}
Authorization: Bearer {{token}}
###
PUT http://localhost:3000/users/{{id}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "about":""
}

###

POST  http://localhost:3000/users/{{id}}/strengths
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "strengths": ["6","8"]
}

###
POST  http://localhost:3000/users/{{id}}/weaknesses
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "weaknesses": ["5","d"]
}

###

GET  http://localhost:3000/users/{{id}}/strengths
Authorization: Bearer {{token}}
###

GET http://localhost:3000/users/{{id}}/weaknesses
Authorization: Bearer {{token}}

###
DELETE http://localhost:3000/users/{{id}}/strengths/a
Authorization: Bearer {{token}}

###
DELETE http://localhost:3000/users/{{id}}/weaknesses/d
Authorization: Bearer {{token}}

###
POST http://localhost:3000/groups
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "group_name": "nhom mới cua huy",
    "description": "test",
    "max_member": "9",
    "chat_type":"Personal"
    
    // chỉ 2 này (Group, Personal)),
}

###
get http://localhost:3000/groups
Authorization: Bearer {{token}}

###
get http://localhost:3000/groups/1/messages/1
Authorization: Bearer {{token}}